import React, { createContext, useContext, useState, useEffect } from 'react';

type Language = 'de' | 'en';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations = {
  de: {
    // Navigation
    'nav.home': 'Startseite',
    'nav.services_packages': 'Leistungen & Pakete',
    'nav.services_overview': 'Leistungsübersicht',
    'nav.pricing_packages': 'Preis-Pakete',
    'nav.book_now': 'Jetzt buchen',
    'nav.about_contact': 'Über uns & Kontakt',
    'nav.about_us': 'Über uns',
    'nav.contact_info': 'Kontaktinformationen',
    'nav.faq': 'FAQ',
    'nav.blog': 'Blog',
    'cta.booking': 'Erstgespräch buchen',
    
    // Products page
    'products.title': 'Virtuelle Assistenz Pakete für Schweizer Unternehmen',
    'products.subtitle': 'Alle Dienstleistungen werden 100% remote von Laura Hähni Office Services mit Sitz in Frauenfeld, Schweiz, erbracht. Keine Vorort-Besuche – nur effiziente, flexible Unterstützung, wo immer Sie sind.',
    'products.starter.title': 'Starter Plan – Ideal für Solo-Unternehmer',
    'products.starter.subtitle': 'Ideal für: Freelancer und Selbstständige, die leichte virtuelle Unterstützung benötigen.',
    'products.business.title': 'Business Plan – Ideal für kleine Teams',
    'products.business.subtitle': 'Ideal für: Kleine Unternehmen, die remote Hilfe bei Finanzen und HR benötigen.',
    'products.pro.title': 'Pro Plan – Ideal für wachsende Unternehmen',
    'products.pro.subtitle': 'Ideal für: Unternehmen mit regelmässigen Admin-Bedürfnissen, die vollständige virtuelle Unterstützung suchen.',
    'products.flexible.title': 'Flexible Unterstützung benötigt?',
    'products.flexible.subtitle': 'Virtuelle Assistenz nach Bedarf',
    'products.custom.title': 'Etwas Individuelles benötigt?',
    'products.custom.subtitle': 'Massgeschneiderte virtuelle Lösungen verfügbar',
    'products.faq.title': 'Häufig gestellte Fragen',
    
    // Contact page
    'contact.title': 'Kontakt',
    'contact.subtitle': 'Ich freue mich zu hören, wie ich Ihr Unternehmen unterstützen kann.',
    'contact.info.title': 'Kontaktinformationen',
    'contact.info.email': 'E-Mail',
    'contact.info.phone': 'Telefon / WhatsApp',
    'contact.info.location': 'Standort',
    'contact.info.location.value': 'Ansässig in Frauenfeld, Schweiz (Nur Remote-Services)',
    'contact.hours.title': 'Geschäftszeiten',
    'contact.hours.weekdays': 'Montag bis Freitag: 08:00 – 12:00 und 14:00 – 18:00',
    'contact.hours.note': 'Support ausserhalb dieser Zeiten kann nach vorheriger Absprache und gegen Aufpreis verfügbar sein.',
    'contact.form.title': 'Kontaktformular',
    'contact.form.name': 'Vollständiger Name',
    'contact.form.email': 'E-Mail-Adresse',
    'contact.form.subject': 'Betreff',
    'contact.form.message': 'Nachricht',
    'contact.form.send': 'Nachricht senden',
    'contact.privacy.title': 'Datenschutzerklärung',
    'contact.privacy.text': 'Ihre persönlichen Daten werden sicher und in Übereinstimmung mit den Schweizer Datenschutzgesetzen behandelt. Ich teile keine Daten mit Dritten und verwende Ihre Angaben nur, um auf Ihre Anfrage zu antworten.',
    
    // FAQ page
    'faq.title': 'FAQ',
    'faq.subtitle': 'Häufig gestellte Fragen zu virtuellen Assistenz-Diensten in der Schweiz.',
    'faq.q1': 'Was macht eine virtuelle Assistentin genau?',
    'faq.a1': 'Eine virtuelle Assistentin übernimmt administrative, organisatorische und finanzielle Aufgaben remote, damit Sie sich auf Ihr Kerngeschäft konzentrieren können. Bei Bürodienstleistungen Hähni umfassen das E-Mail-Management, Terminplanung, Buchhaltung, Personaladministration und mehr – alles 100% digital und flexibel. Im Gegensatz zu traditionellen Büros bieten wir Schweizer Präzision ohne Vor-Ort-Präsenz.\n\nVorteile: Sparen Sie bis zu 30% an internen Kosten durch Outsourcing.\n\n→ Mehr zu unseren Leistungen unter /leistungen\n→ Bereit zu starten? Buchen Sie ein kostenloses Erstgespräch unter /buchung',
    'faq.q2': 'Welche Vorteile hat die Einstellung einer virtuellen Assistentin für KMU in der Schweiz?',
    'faq.a2': 'Virtuelle Assistenz entlastet Schweizer KMU von Routineaufgaben wie Buchhaltung oder HR, was Zeit und Kosten spart. Unsere USPs: Flexible Abrechnung (ab CHF 60/Stunde), volle Datensicherheit nach DSG und persönliche Betreuung. Kunden berichten von 20-40% mehr Fokus auf Wachstum. Ideal für Freelancer und Startups in Frauenfeld oder Zürich.\n\nTipp: Keine Fixkosten wie bei Festanstellungen – nur bei Bedarf zahlen.\n\n→ Erfahren Sie mehr über unsere Pakete unter /products\n→ Kontaktieren Sie uns für ein individuelles Angebot',
    'faq.q3': 'Wie viel kostet eine virtuelle Assistentin in der Schweiz?',
    'faq.a3': 'Die Kosten variieren je nach Umfang: Bei uns starten Stundenpreise bei CHF 60 für virtuelle Assistenz und CHF 70 für Buchhaltung. Pauschalpakete (z. B. 5 Std./Monat für CHF 290) bieten Rabatte für Planungssicherheit. Keine versteckten Gebühren – transparente Abrechnung pro 15 Minuten. Im Vergleich zu Inhouse-Mitarbeitern sparen Sie Lohnnebenkosten und Sozialabgaben.\n\nBeispiel: Ein Monatspaket „Pro" (20 Std.) kostet CHF 990.\n\n→ Sehen Sie alle Preise unter /products\n→ Fordern Sie eine Offerte unter /kontakt an',
    'faq.q4': 'Sind meine Daten sicher bei einer virtuellen Assistentin?',
    'faq.a4': 'Ja, absolut – wir halten uns streng an Schweizer Datenschutzgesetze (DSG) und EU-DSGVO. Daten werden über sichere Tools wie Dropbox oder bexio ausgetauscht, mit Verschlüsselung und Vertraulichkeitsvereinbarungen. Kein Zugriff Dritter, regelmäßige Backups. Unsere Kunden schätzen diese Transparenz als Kern unserer Swiss-Quality-Philosophie.\n\nZusätzlich: Auf Wunsch NDAs verfügbar.\n\n→ Lesen Sie unsere Datenschutzerklärung\n→ Haben Sie Fragen? Kontaktieren Sie uns unter /kontakt',
    'faq.q5': 'Muss ich vor Ort sein, um mit einer virtuellen Assistentin zusammenzuarbeiten?',
    'faq.a5': 'Nein, unsere Dienste sind 100% remote – perfekt für Kunden in der ganzen Schweiz oder DACH-Region. Kommunikation via Zoom, E-Mail oder Slack; Dokumente digital via Cloud. Das spart Reisekosten und ermöglicht Flexibilität, z. B. für Home-Office-Teams. Persönliche Treffen in Frauenfeld nur auf Wunsch.\n\nVorteil: Starten Sie innerhalb von 1-3 Tagen nach dem Erstgespräch.\n\n→ Mehr zum Ablauf\n→ Buchen Sie jetzt unter /buchung',
    'faq.q6': 'Gibt es Mindestlaufzeiten oder Verträge für virtuelle Assistenz?',
    'faq.a6': 'Nein, wir bieten maximale Flexibilität ohne Mindestlaufzeiten. Buchen Sie ad-hoc für Spitzenlasten oder monatlich für laufende Unterstützung. Kündigung jederzeit möglich – wir bauen auf langfristiges Vertrauen, nicht auf Verträge. Ideal für saisonale Bedürfnisse von Schweizer Startups.\n\nOption: Pauschalen für Rabatte bei Daueraufträgen.\n\n→ Entdecken Sie unsere Modelle unter /products\n→ Lassen Sie uns reden unter /kontakt',
    'faq.q7': 'Wie schnell kann ich mit einer virtuellen Assistentin starten?',
    'faq.a7': 'Meist innerhalb von 1-3 Werktagen: Nach einem kostenlosen 30-minütigen Erstgespräch (via Zoom) erhalten Sie eine Offerte. Danach starten wir remote. Für dringende Fälle priorisieren wir – z. B. bei Steuerfristen oder Events. Unsere Effizienz ist ein Top-USP für KMU.\n\nTipp: Nutzen Sie unseren Online-Kalender für schnelle Buchung.\n\n→ Buchen Sie hier unter /buchung',
    'faq.q8': 'Kann eine virtuelle Assistentin meine Buchhaltung übernehmen?',
    'faq.a8': 'Ja, als zertifizierte Buchhalterin übernehme ich Finanzbuchhaltung, MWST-Abrechnungen, Rechnungsstellung und Steuererklärungen – alles digital mit Tools wie bexio. Speziell für Schweizer KMU: Vorbereitung für Jahresabschlüsse und Quellensteuer. Sparen Sie Zeit und vermeiden Sie Fehler.\n\nBeispiel: Digitale Belegverwaltung via Google Drive.\n\n→ Details zur Buchhaltung unter /leistungen\n→ Fordern Sie Hilfe an unter /kontakt',
    'faq.q9': 'Welche Tools nutzt eine virtuelle Assistentin?',
    'faq.a9': 'Wir arbeiten mit bewährten Tools wie bexio (Buchhaltung), Slack/Teams (Kommunikation), Google Workspace/Dropbox (Dokumente) und Zoom (Meetings). Auf Wunsch integrieren wir Ihre Systeme oder empfehlen Optimierungen für Digitalisierung. Alles sicher und skalierbar.\n\nVorteil: Keine Lernkurve für Sie.\n\n→ Mehr zu Tools\n→ Kontakt für Beratung unter /kontakt',
    'faq.q10': 'Warum eine virtuelle Assistentin aus der Schweiz wählen?',
    'faq.a10': 'Schweizer Qualität bedeutet Zuverlässigkeit, Präzision und Diskretion – plus Kenntnisse lokaler Gesetze (z. B. AHV, MWST). Als Sitz in Frauenfeld bieten wir persönliche Nähe mit globaler Flexibilität. Kunden wählen uns für die Mischung aus Effizienz und Wärme.\n\nTestimonial: „Laura hat unsere Admin digitalisiert – top!" (Patrick S., Zürich).\n\n→ Über uns unter /ueber-uns\n→ Starten Sie Ihr Projekt unter /kontakt',
    'faq.cta.title': 'Haben Sie noch Fragen?',
    'faq.cta.subtitle': 'Wir sind hier, um zu helfen! Kontaktieren Sie uns für eine persönliche Beratung.',
    'faq.cta.email': 'E-Mail senden',
    'faq.cta.call': 'Jetzt anrufen',
    'faq.links.packages': 'Unsere Pakete ansehen',
    'faq.links.booking': 'Termin buchen',
    'faq.links.contact': 'Kontakt aufnehmen',
    'faq.privacy': 'Ihre Privatsphäre ist uns wichtig. Die bereitgestellten Informationen werden ausschliesslich zur Beantwortung Ihrer Anfrage verwendet und gemäss den geltenden Datenschutzgesetzen behandelt.',
    
    // Home page
    'home.trust.title': 'Warum Bürodienstleistungen Hähni?',
    'home.trust.subtitle': 'Damit Sie sich auf Ihr Kerngeschäft konzentrieren können',
    'home.trust.experience': 'Jahre Erfahrung',
    'home.trust.experience_desc': 'Langjährige Expertise in der kaufmännischen Sachbearbeitung',
    'home.trust.remote': 'Remote',
    'home.trust.remote_desc': 'Vollständig digitale Abwicklung - keine Vor-Ort-Termine nötig',
    'home.trust.flexible': 'Flexibel',
    'home.trust.flexible_desc': 'Anpassung an Ihre Bedürfnisse und Arbeitszeiten',
    'home.cta.title': 'Bereit für Ihr kostenloses Erstgespräch?',
    'home.cta.subtitle': 'Lassen Sie uns besprechen, wie wir Ihr Backoffice optimieren können.',
    'home.cta.book': 'Jetzt Termin vereinbaren',
    'home.cta.learn_more': 'Mehr erfahren',
    
    // Pricing 2025
    'pricing.title': 'Unsere Preispakete 2025',
    'pricing.subtitle': 'Transparente Preise für professionelle Bürodienstleistungen. Alle Pakete inkl. persönlicher Betreuung und flexibler Abrechnung.',
    'pricing.cta.request': 'Jetzt anfragen',
    'pricing.cta.details': 'Alle Details ansehen',

    // Buchhaltung (Accounting)
    'pricing.accounting.title': 'Buchhaltung',
    'pricing.accounting.description': 'Professionelle Buchführung und Finanzadministration für Ihr Unternehmen',
    'pricing.accounting.mini.name': 'Mini',
    'pricing.accounting.mini.included': 'bis 40 Belege',
    'pricing.accounting.mini.hours': '3 Std',
    'pricing.accounting.mini.price': 'CHF 300',
    'pricing.accounting.mini.extra': 'Mehrbelege: CHF 2/Beleg',
    'pricing.accounting.standard.name': 'Standard',
    'pricing.accounting.standard.included': 'bis 100 Belege',
    'pricing.accounting.standard.hours': '6 Std',
    'pricing.accounting.standard.price': 'CHF 540',
    'pricing.accounting.business.name': 'Business',
    'pricing.accounting.business.included': 'bis 200 Belege',
    'pricing.accounting.business.hours': '10 Std',
    'pricing.accounting.business.price': 'CHF 900',
    'pricing.accounting.plus.name': 'Plus',
    'pricing.accounting.plus.included': 'bis 300 Belege',
    'pricing.accounting.plus.hours': '14 Std',
    'pricing.accounting.plus.price': 'CHF 1\'050',

    // Lohnadministration (Payroll)
    'pricing.payroll.title': 'Lohnadministration',
    'pricing.payroll.description': 'Komplette Lohnabrechnung und Personaladministration',
    'pricing.payroll.basic.name': 'Basic',
    'pricing.payroll.basic.included': '1 Lohn',
    'pricing.payroll.basic.hours': '0.75 Std',
    'pricing.payroll.basic.price': 'CHF 75',
    'pricing.payroll.basic.extra': 'Mehrlöhne: CHF 25/Lohn',
    'pricing.payroll.standard.name': 'Standard',
    'pricing.payroll.standard.included': 'bis 3 Löhne',
    'pricing.payroll.standard.hours': '2 Std',
    'pricing.payroll.standard.price': 'CHF 180',
    'pricing.payroll.business.name': 'Business',
    'pricing.payroll.business.included': 'bis 8 Löhne',
    'pricing.payroll.business.hours': '4.5 Std',
    'pricing.payroll.business.price': 'CHF 405',
    'pricing.payroll.plus.name': 'Plus',
    'pricing.payroll.plus.included': 'bis 15 Löhne',
    'pricing.payroll.plus.hours': '8 Std',
    'pricing.payroll.plus.price': 'CHF 600',

    // Personaladministration (HR Admin)
    'pricing.hr.title': 'Personaladministration',
    'pricing.hr.description': 'HR-Verwaltung und Personalbetreuung',
    'pricing.hr.basic.name': 'Basic',
    'pricing.hr.basic.included': '1 Mutation',
    'pricing.hr.basic.hours': '0.75 Std',
    'pricing.hr.basic.price': 'CHF 75',
    'pricing.hr.basic.extra': 'Mehrmutationen: CHF 25',
    'pricing.hr.standard.name': 'Standard',
    'pricing.hr.standard.included': 'bis 3 Mutationen',
    'pricing.hr.standard.hours': '2 Std',
    'pricing.hr.standard.price': 'CHF 180',
    'pricing.hr.business.name': 'Business',
    'pricing.hr.business.included': 'bis 5 Mutationen',
    'pricing.hr.business.hours': '3.5 Std',
    'pricing.hr.business.price': 'CHF 315',
    'pricing.hr.plus.name': 'Plus',
    'pricing.hr.plus.included': 'unbegrenzt',
    'pricing.hr.plus.hours': '',
    'pricing.hr.plus.price': 'CHF 450',

    // Zahlungsläufe & Mahnwesen (Payments & Dunning)
    'pricing.payments.title': 'Zahlungsläufe & Mahnwesen',
    'pricing.payments.description': 'Professionelle Abwicklung von Zahlungen und Mahnungen',
    'pricing.payments.mini.name': 'Mini',
    'pricing.payments.mini.included': '10 Zahlungen/5 Mahnungen',
    'pricing.payments.mini.hours': '1.25 Std',
    'pricing.payments.mini.price': 'CHF 125',
    'pricing.payments.mini.extra': 'Mehrbelege: CHF 2',
    'pricing.payments.standard.name': 'Standard',
    'pricing.payments.standard.included': 'bis 25/10',
    'pricing.payments.standard.hours': '2.5 Std',
    'pricing.payments.standard.price': 'CHF 225',
    'pricing.payments.business.name': 'Business',
    'pricing.payments.business.included': 'bis 40/20',
    'pricing.payments.business.hours': '3.5 Std',
    'pricing.payments.business.price': 'CHF 315',

    // Virtuelle Assistenz (Virtual Assistant)
    'pricing.virtual.title': 'Virtuelle Assistenz',
    'pricing.virtual.description': 'Flexible administrative Unterstützung für Ihre Geschäftstätigkeit',
    'pricing.virtual.light.name': 'Light',
    'pricing.virtual.light.included': '1 Std',
    'pricing.virtual.light.hours': '',
    'pricing.virtual.light.price': 'CHF 100',
    'pricing.virtual.light.extra': 'Mehrstunden: CHF 100/h',
    'pricing.virtual.standard.name': 'Standard',
    'pricing.virtual.standard.included': '3 Std',
    'pricing.virtual.standard.hours': '',
    'pricing.virtual.standard.price': 'CHF 270',
    'pricing.virtual.standard.extra': 'Mehrstunden: CHF 90/h',
    'pricing.virtual.business.name': 'Business',
    'pricing.virtual.business.included': '5 Std',
    'pricing.virtual.business.hours': '',
    'pricing.virtual.business.price': 'CHF 375',
    'pricing.virtual.business.extra': 'Mehrstunden: CHF 75/h',
    'pricing.virtual.max.name': 'Max',
    'pricing.virtual.max.included': '10 Std',
    'pricing.virtual.max.hours': '',
    'pricing.virtual.max.price': 'CHF 750',

    // Kommunikation & Organisation (Communication & Organization)
    'pricing.communication.title': 'Kommunikation & Organisation',
    'pricing.communication.description': 'Professionelle Kommunikation und organisatorische Unterstützung',
    'pricing.communication.kompakt.name': 'Kompakt',
    'pricing.communication.kompakt.included': '1 Std',
    'pricing.communication.kompakt.hours': '',
    'pricing.communication.kompakt.price': 'CHF 100',
    'pricing.communication.kompakt.extra': 'Mehrstunden: CHF 100/h',
    'pricing.communication.standard.name': 'Standard',
    'pricing.communication.standard.included': '3 Std',
    'pricing.communication.standard.hours': '',
    'pricing.communication.standard.price': 'CHF 270',
    'pricing.communication.standard.extra': 'Mehrstunden: CHF 90/h',
    'pricing.communication.intensiv.name': 'Intensiv',
    'pricing.communication.intensiv.included': '5 Std',
    'pricing.communication.intensiv.hours': '',
    'pricing.communication.intensiv.price': 'CHF 375',
    'pricing.communication.intensiv.extra': 'Mehrstunden: CHF 75/h',
    'pricing.communication.max.name': 'Max',
    'pricing.communication.max.included': '10 Std',
    'pricing.communication.max.hours': '',
    'pricing.communication.max.price': 'CHF 750',

    // Spesenverarbeitung (Expense Processing)
    'pricing.expenses.title': 'Spesenverarbeitung',
    'pricing.expenses.description': 'Effiziente Verarbeitung und Verwaltung Ihrer Spesenbelege',
    'pricing.expenses.mini.name': 'Mini',
    'pricing.expenses.mini.included': 'bis 10 Belege',
    'pricing.expenses.mini.hours': '1 Std',
    'pricing.expenses.mini.price': 'CHF 100',
    'pricing.expenses.mini.extra': 'Mehrbelege: CHF 2',
    'pricing.expenses.standard.name': 'Standard',
    'pricing.expenses.standard.included': 'bis 25 Belege',
    'pricing.expenses.standard.hours': '2 Std',
    'pricing.expenses.standard.price': 'CHF 180',
    'pricing.expenses.business.name': 'Business',
    'pricing.expenses.business.included': 'bis 50 Belege',
    'pricing.expenses.business.hours': '3.5 Std',
    'pricing.expenses.business.price': 'CHF 315',
    'pricing.expenses.plus.name': 'Plus',
    'pricing.expenses.plus.included': 'bis 80 Belege',
    'pricing.expenses.plus.hours': '5 Std',
    'pricing.expenses.plus.price': 'CHF 375',
    'pricing.expenses.max.name': 'Max',
    'pricing.expenses.max.included': '100+ Belege',
    'pricing.expenses.max.hours': '10 Std',
    'pricing.expenses.max.price': 'CHF 750',

    // Mailbetreuung (Mail Support)
    'pricing.mail.title': 'Mailbetreuung',
    'pricing.mail.description': 'Professionelle E-Mail-Verwaltung und Korrespondenz',
    'pricing.mail.mini.name': 'Mini',
    'pricing.mail.mini.included': '1 Std',
    'pricing.mail.mini.hours': '',
    'pricing.mail.mini.price': 'CHF 100',
    'pricing.mail.mini.extra': 'Mehrstunden: CHF 100/h',
    'pricing.mail.standard.name': 'Standard',
    'pricing.mail.standard.included': '3 Std',
    'pricing.mail.standard.hours': '',
    'pricing.mail.standard.price': 'CHF 270',
    'pricing.mail.standard.extra': 'Mehrstunden: CHF 90/h',
    'pricing.mail.business.name': 'Business',
    'pricing.mail.business.included': '5 Std',
    'pricing.mail.business.hours': '',
    'pricing.mail.business.price': 'CHF 375',
    'pricing.mail.business.extra': 'Mehrstunden: CHF 75/h',
    'pricing.mail.max.name': 'Max',
    'pricing.mail.max.included': '10 Std',
    'pricing.mail.max.hours': '',
    'pricing.mail.max.price': 'CHF 750',
  },
  en: {
    // Navigation
    'nav.home': 'Home',
    'nav.services_packages': 'Services & Packages',
    'nav.services_overview': 'Services Overview',
    'nav.pricing_packages': 'Pricing Packages',
    'nav.book_now': 'Book Now',
    'nav.about_contact': 'About & Contact',
    'nav.about_us': 'About Us',
    'nav.contact_info': 'Contact Info',
    'nav.faq': 'FAQ',
    'nav.blog': 'Blog',
    'cta.booking': 'Book Consultation',
    
    // Products page
    'products.title': 'Virtual Assistant Packages for Swiss Businesses',
    'products.subtitle': 'All services are delivered 100% remotely by Laura Hähni Office Services, based in Frauenfeld, Switzerland. No on-site visits – just efficient, flexible support wherever you are.',
    'products.starter.title': 'Starter Plan – Best for Solo Entrepreneurs',
    'products.starter.subtitle': 'Ideal for: Freelancers and independent professionals needing light virtual support.',
    'products.business.title': 'Business Plan – Best for Small Teams',
    'products.business.subtitle': 'Ideal for: Small businesses needing remote help with finance and HR.',
    'products.pro.title': 'Pro Plan – Best for Growing Companies',
    'products.pro.subtitle': 'Ideal for: Businesses with regular admin needs seeking full virtual support.',
    'products.flexible.title': 'Need Flexible Support?',
    'products.flexible.subtitle': 'On-Demand Virtual Assistance',
    'products.custom.title': 'Need Something Custom?',
    'products.custom.subtitle': 'Tailored Virtual Solutions Available',
    'products.faq.title': 'Frequently Asked Questions',
    
    // Contact page
    'contact.title': 'Contact',
    'contact.subtitle': 'I\'d love to hear how I can support your business.',
    'contact.info.title': 'Contact Information',
    'contact.info.email': 'Email',
    'contact.info.phone': 'Phone / WhatsApp',
    'contact.info.location': 'Location',
    'contact.info.location.value': 'Based in Frauenfeld, Switzerland (Remote-only services)',
    'contact.hours.title': 'Business Hours',
    'contact.hours.weekdays': 'Monday to Friday: 08:00 – 12:00 and 14:00 – 18:00',
    'contact.hours.note': 'Support outside these hours may be available with prior agreement and surcharge.',
    'contact.form.title': 'Contact Form',
    'contact.form.name': 'Full Name',
    'contact.form.email': 'Email Address',
    'contact.form.subject': 'Subject',
    'contact.form.message': 'Message',
    'contact.form.send': 'Send Message',
    'contact.privacy.title': 'Privacy Statement',
    'contact.privacy.text': 'Your personal information is handled securely and in accordance with Swiss data protection laws. I do not share data with third parties and will only use your details to respond to your inquiry.',
    
    // FAQ page
    'faq.title': 'FAQ',
    'faq.subtitle': 'Frequently asked questions about virtual assistant services in Switzerland.',
    'faq.q1': 'What exactly does a virtual assistant do?',
    'faq.a1': 'A virtual assistant handles administrative, organizational, and financial tasks remotely, allowing you to focus on your core business. At Bürodienstleistungen Hähni, this includes email management, scheduling, bookkeeping, HR admin, and more – all 100% digital and flexible. Unlike traditional offices, we offer Swiss precision without on-site presence.\n\nBenefits: Save up to 30% on internal costs through outsourcing.\n\n→ More about our services at /services\n→ Ready to start? Book a free consultation at /booking',
    'faq.q2': 'What are the benefits of hiring a virtual assistant for SMEs in Switzerland?',
    'faq.a2': 'Virtual assistance relieves Swiss SMEs of routine tasks like bookkeeping or HR, saving time and costs. Our USPs: Flexible billing (from CHF 60/hour), full data security under DSG, and personal support. Clients report 20-40% more focus on growth. Ideal for freelancers and startups in Frauenfeld or Zurich.\n\nTip: No fixed costs like with permanent hires – pay only as needed.\n\n→ Learn about our packages at /products\n→ Contact us for a custom quote',
    'faq.q3': 'How much does a virtual assistant cost in Switzerland?',
    'faq.a3': 'Costs vary by scope: Our hourly rates start at CHF 60 for virtual assistance and CHF 70 for bookkeeping. Flat-rate packages (e.g., 5 hrs/month for CHF 290) offer discounts for predictability. No hidden fees – transparent billing per 15 minutes. Compared to in-house staff, you save on overheads and social contributions.\n\nExample: "Pro" monthly package (20 hrs) at CHF 990.\n\n→ View all pricing at /products\n→ Request a quote at /contact',
    'faq.q4': 'Is my data secure with a virtual assistant?',
    'faq.a4': 'Yes, absolutely – we strictly adhere to Swiss data protection laws (DSG) and EU GDPR. Data is exchanged via secure tools like Dropbox or bexio, with encryption and confidentiality agreements. No third-party access, regular backups. Our clients value this transparency as core to our Swiss-quality philosophy.\n\nAdditional: NDAs upon request.\n\n→ Read our privacy policy\n→ Have questions? Contact us at /contact',
    'faq.q5': 'Do I need to be on-site to work with a virtual assistant?',
    'faq.a5': 'No, our services are 100% remote – perfect for clients across Switzerland or the DACH region. Communication via Zoom, email, or Slack; documents digitally via cloud. This saves travel costs and enables flexibility, e.g., for home-office teams. Personal meetings in Frauenfeld only if desired.\n\nAdvantage: Start within 1-3 days after the initial consultation.\n\n→ More on the process\n→ Book now at /booking',
    'faq.q6': 'Are there minimum contract terms for virtual assistance?',
    'faq.a6': 'No, we offer maximum flexibility without minimum terms. Book ad-hoc for peak loads or monthly for ongoing support. Cancellation anytime – we build on long-term trust, not contracts. Ideal for seasonal needs of Swiss startups.\n\nOption: Flat rates for discounts on ongoing orders.\n\n→ Discover our models at /products\n→ Let\'s talk at /contact',
    'faq.q7': 'How quickly can I start with a virtual assistant?',
    'faq.a7': 'Usually within 1-3 business days: After a free 30-minute initial consultation (via Zoom), you get a quote. Then we start remotely. For urgent cases, we prioritize – e.g., tax deadlines or events. Our efficiency is a top USP for SMEs.\n\nTip: Use our online calendar for quick booking.\n\n→ Book here at /booking',
    'faq.q8': 'Can a virtual assistant handle my bookkeeping?',
    'faq.a8': 'Yes, as a certified accountant, I handle financial bookkeeping, VAT settlements, invoicing, and tax returns – all digitally with tools like bexio. Specifically for Swiss SMEs: Preparation for annual closings and withholding taxes. Save time and avoid errors.\n\nExample: Digital receipt management via Google Drive.\n\n→ Bookkeeping details at /services\n→ Request help at /contact',
    'faq.q9': 'What tools does a virtual assistant use?',
    'faq.a9': 'We work with proven tools like bexio (bookkeeping), Slack/Teams (communication), Google Workspace/Dropbox (documents), and Zoom (meetings). Upon request, we integrate your systems or recommend optimizations for digitization. All secure and scalable.\n\nAdvantage: No learning curve for you.\n\n→ More on tools\n→ Contact for advice at /contact',
    'faq.q10': 'Why choose a virtual assistant from Switzerland?',
    'faq.a10': 'Swiss quality means reliability, precision, and discretion – plus knowledge of local laws (e.g., AHV, VAT). Based in Frauenfeld, we offer personal proximity with global flexibility. Clients choose us for the blend of efficiency and warmth.\n\nTestimonial: "Laura digitized our admin – top!" (Patrick S., Zurich).\n\n→ About us at /about\n→ Start your project at /contact',
    'faq.cta.title': 'Still Have Questions?',
    'faq.cta.subtitle': 'We\'re here to help! Get in touch for a personalized consultation.',
    'faq.cta.email': 'Send us an Email',
    'faq.cta.call': 'Call us Now',
    'faq.links.packages': 'View Our Packages',
    'faq.links.booking': 'Book Appointment',
    'faq.links.contact': 'Get in Touch',
    'faq.privacy': 'Your privacy is important to us. Information provided will be used solely to respond to your inquiry and handled in accordance with applicable data protection laws.',
    
    // Home page
    'home.trust.title': 'Why Choose Laura Hähni Office Services?',
    'home.trust.subtitle': 'So you can focus on your core business',
    'home.trust.experience': 'Years Experience',
    'home.trust.experience_desc': 'Long-standing expertise in commercial administration',
    'home.trust.remote': 'Remote',
    'home.trust.remote_desc': 'Completely digital processing - no on-site appointments needed',
    'home.trust.flexible': 'Flexible',
    'home.trust.flexible_desc': 'Adaptation to your needs and working hours',
    'home.cta.title': 'Ready for your free initial consultation?',
    'home.cta.subtitle': 'Let\'s discuss how we can optimize your back office.',
    'home.cta.book': 'Schedule Appointment Now',
    'home.cta.learn_more': 'Learn More',
    
    // Pricing 2025
    'pricing.title': 'Our 2025 Pricing Packages',
    'pricing.subtitle': 'Transparent pricing for professional office services. All packages include personal support and flexible billing.',
    'pricing.cta.request': 'Request Quote',
    'pricing.cta.details': 'View All Details',

    // Accounting
    'pricing.accounting.title': 'Accounting',
    'pricing.accounting.description': 'Professional bookkeeping and financial administration for your company',
    'pricing.accounting.mini.name': 'Mini',
    'pricing.accounting.mini.included': 'up to 40 receipts',
    'pricing.accounting.mini.hours': '3 hrs',
    'pricing.accounting.mini.price': 'CHF 300',
    'pricing.accounting.mini.extra': 'Additional receipts: CHF 2/receipt',
    'pricing.accounting.standard.name': 'Standard',
    'pricing.accounting.standard.included': 'up to 100 receipts',
    'pricing.accounting.standard.hours': '6 hrs',
    'pricing.accounting.standard.price': 'CHF 540',
    'pricing.accounting.business.name': 'Business',
    'pricing.accounting.business.included': 'up to 200 receipts',
    'pricing.accounting.business.hours': '10 hrs',
    'pricing.accounting.business.price': 'CHF 900',
    'pricing.accounting.plus.name': 'Plus',
    'pricing.accounting.plus.included': 'up to 300 receipts',
    'pricing.accounting.plus.hours': '14 hrs',
    'pricing.accounting.plus.price': 'CHF 1,050',

    // Payroll Administration
    'pricing.payroll.title': 'Payroll Administration',
    'pricing.payroll.description': 'Complete payroll processing and personnel administration',
    'pricing.payroll.basic.name': 'Basic',
    'pricing.payroll.basic.included': '1 payroll',
    'pricing.payroll.basic.hours': '0.75 hrs',
    'pricing.payroll.basic.price': 'CHF 75',
    'pricing.payroll.basic.extra': 'Additional payrolls: CHF 25/payroll',
    'pricing.payroll.standard.name': 'Standard',
    'pricing.payroll.standard.included': 'up to 3 payrolls',
    'pricing.payroll.standard.hours': '2 hrs',
    'pricing.payroll.standard.price': 'CHF 180',
    'pricing.payroll.business.name': 'Business',
    'pricing.payroll.business.included': 'up to 8 payrolls',
    'pricing.payroll.business.hours': '4.5 hrs',
    'pricing.payroll.business.price': 'CHF 405',
    'pricing.payroll.plus.name': 'Plus',
    'pricing.payroll.plus.included': 'up to 15 payrolls',
    'pricing.payroll.plus.hours': '8 hrs',
    'pricing.payroll.plus.price': 'CHF 600',

    // HR Administration
    'pricing.hr.title': 'HR Administration',
    'pricing.hr.description': 'HR management and personnel support',
    'pricing.hr.basic.name': 'Basic',
    'pricing.hr.basic.included': '1 change',
    'pricing.hr.basic.hours': '0.75 hrs',
    'pricing.hr.basic.price': 'CHF 75',
    'pricing.hr.basic.extra': 'Additional changes: CHF 25',
    'pricing.hr.standard.name': 'Standard',
    'pricing.hr.standard.included': 'up to 3 changes',
    'pricing.hr.standard.hours': '2 hrs',
    'pricing.hr.standard.price': 'CHF 180',
    'pricing.hr.business.name': 'Business',
    'pricing.hr.business.included': 'up to 5 changes',
    'pricing.hr.business.hours': '3.5 hrs',
    'pricing.hr.business.price': 'CHF 315',
    'pricing.hr.plus.name': 'Plus',
    'pricing.hr.plus.included': 'unlimited',
    'pricing.hr.plus.hours': '',
    'pricing.hr.plus.price': 'CHF 450',

    // Payments & Dunning
    'pricing.payments.title': 'Payments & Dunning',
    'pricing.payments.description': 'Professional processing of payments and reminders',
    'pricing.payments.mini.name': 'Mini',
    'pricing.payments.mini.included': '10 payments/5 reminders',
    'pricing.payments.mini.hours': '1.25 hrs',
    'pricing.payments.mini.price': 'CHF 125',
    'pricing.payments.mini.extra': 'Additional items: CHF 2',
    'pricing.payments.standard.name': 'Standard',
    'pricing.payments.standard.included': 'up to 25/10',
    'pricing.payments.standard.hours': '2.5 hrs',
    'pricing.payments.standard.price': 'CHF 225',
    'pricing.payments.business.name': 'Business',
    'pricing.payments.business.included': 'up to 40/20',
    'pricing.payments.business.hours': '3.5 hrs',
    'pricing.payments.business.price': 'CHF 315',

    // Virtual Assistant
    'pricing.virtual.title': 'Virtual Assistant',
    'pricing.virtual.description': 'Flexible administrative support for your business activities',
    'pricing.virtual.light.name': 'Light',
    'pricing.virtual.light.included': '1 hr',
    'pricing.virtual.light.hours': '',
    'pricing.virtual.light.price': 'CHF 100',
    'pricing.virtual.light.extra': 'Additional hours: CHF 100/hr',
    'pricing.virtual.standard.name': 'Standard',
    'pricing.virtual.standard.included': '3 hrs',
    'pricing.virtual.standard.hours': '',
    'pricing.virtual.standard.price': 'CHF 270',
    'pricing.virtual.standard.extra': 'Additional hours: CHF 90/hr',
    'pricing.virtual.business.name': 'Business',
    'pricing.virtual.business.included': '5 hrs',
    'pricing.virtual.business.hours': '',
    'pricing.virtual.business.price': 'CHF 375',
    'pricing.virtual.business.extra': 'Additional hours: CHF 75/hr',
    'pricing.virtual.max.name': 'Max',
    'pricing.virtual.max.included': '10 hrs',
    'pricing.virtual.max.hours': '',
    'pricing.virtual.max.price': 'CHF 750',

    // Communication & Organization
    'pricing.communication.title': 'Communication & Organization',
    'pricing.communication.description': 'Professional communication and organizational support',
    'pricing.communication.kompakt.name': 'Compact',
    'pricing.communication.kompakt.included': '1 hr',
    'pricing.communication.kompakt.hours': '',
    'pricing.communication.kompakt.price': 'CHF 100',
    'pricing.communication.kompakt.extra': 'Additional hours: CHF 100/hr',
    'pricing.communication.standard.name': 'Standard',
    'pricing.communication.standard.included': '3 hrs',
    'pricing.communication.standard.hours': '',
    'pricing.communication.standard.price': 'CHF 270',
    'pricing.communication.standard.extra': 'Additional hours: CHF 90/hr',
    'pricing.communication.intensiv.name': 'Intensive',
    'pricing.communication.intensiv.included': '5 hrs',
    'pricing.communication.intensiv.hours': '',
    'pricing.communication.intensiv.price': 'CHF 375',
    'pricing.communication.intensiv.extra': 'Additional hours: CHF 75/hr',
    'pricing.communication.max.name': 'Max',
    'pricing.communication.max.included': '10 hrs',
    'pricing.communication.max.hours': '',
    'pricing.communication.max.price': 'CHF 750',

    // Expense Processing
    'pricing.expenses.title': 'Expense Processing',
    'pricing.expenses.description': 'Efficient processing and management of your expense receipts',
    'pricing.expenses.mini.name': 'Mini',
    'pricing.expenses.mini.included': 'up to 10 receipts',
    'pricing.expenses.mini.hours': '1 hr',
    'pricing.expenses.mini.price': 'CHF 100',
    'pricing.expenses.mini.extra': 'Additional receipts: CHF 2',
    'pricing.expenses.standard.name': 'Standard',
    'pricing.expenses.standard.included': 'up to 25 receipts',
    'pricing.expenses.standard.hours': '2 hrs',
    'pricing.expenses.standard.price': 'CHF 180',
    'pricing.expenses.business.name': 'Business',
    'pricing.expenses.business.included': 'up to 50 receipts',
    'pricing.expenses.business.hours': '3.5 hrs',
    'pricing.expenses.business.price': 'CHF 315',
    'pricing.expenses.plus.name': 'Plus',
    'pricing.expenses.plus.included': 'up to 80 receipts',
    'pricing.expenses.plus.hours': '5 hrs',
    'pricing.expenses.plus.price': 'CHF 375',
    'pricing.expenses.max.name': 'Max',
    'pricing.expenses.max.included': '100+ receipts',
    'pricing.expenses.max.hours': '10 hrs',
    'pricing.expenses.max.price': 'CHF 750',

    // Mail Support
    'pricing.mail.title': 'Mail Support',
    'pricing.mail.description': 'Professional email management and correspondence',
    'pricing.mail.mini.name': 'Mini',
    'pricing.mail.mini.included': '1 hr',
    'pricing.mail.mini.hours': '',
    'pricing.mail.mini.price': 'CHF 100',
    'pricing.mail.mini.extra': 'Additional hours: CHF 100/hr',
    'pricing.mail.standard.name': 'Standard',
    'pricing.mail.standard.included': '3 hrs',
    'pricing.mail.standard.hours': '',
    'pricing.mail.standard.price': 'CHF 270',
    'pricing.mail.standard.extra': 'Additional hours: CHF 90/hr',
    'pricing.mail.business.name': 'Business',
    'pricing.mail.business.included': '5 hrs',
    'pricing.mail.business.hours': '',
    'pricing.mail.business.price': 'CHF 375',
    'pricing.mail.business.extra': 'Additional hours: CHF 75/hr',
    'pricing.mail.max.name': 'Max',
    'pricing.mail.max.included': '10 hrs',
    'pricing.mail.max.hours': '',
    'pricing.mail.max.price': 'CHF 750',
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('en');

  useEffect(() => {
    const saved = localStorage.getItem('language') as Language;
    if (saved && (saved === 'de' || saved === 'en')) {
      setLanguage(saved);
    } else {
      // Always default to English if no saved language
      setLanguage('en');
      localStorage.setItem('language', 'en');
    }
  }, []);

  const handleSetLanguage = (lang: Language) => {
    setLanguage(lang);
    localStorage.setItem('language', lang);
  };

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage: handleSetLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};